// Config repository — the ONLY things this app persists in a database: dashboard
// layouts, CalDAV account credentials, and CalDAV list selections (plus login
// sessions, which are just as disposable). Everything else — tasks, projects,
// labels, reminders — lives in the user's CalDAV server, never here.
//
// Two interchangeable backends behind CONFIG_STORE (default postgres; sqlite is
// the target). The SQLite handle is opened SYNCHRONOUSLY at import so the session
// store can be constructed at app-setup time, before start() runs.
import session from 'express-session'
import connectPgSimple from 'connect-pg-simple'
import sqliteStoreFactory from 'better-sqlite3-session-store'
import Database from 'better-sqlite3'
import { pool } from './db.js'

export const CONFIG_STORE = (process.env.CONFIG_STORE || 'postgres') === 'sqlite' ? 'sqlite' : 'postgres'
const isSqlite = CONFIG_STORE === 'sqlite'

// ---- SQLite handle (opened eagerly when selected) ----
export let sqlite = null
if (isSqlite) {
  const path = process.env.CONFIG_DB_PATH
  if (!path) { console.error('FATAL: CONFIG_STORE=sqlite requires CONFIG_DB_PATH'); process.exit(1) }
  sqlite = new Database(path)
  sqlite.pragma('journal_mode = WAL')      // safe on ceph-rbd BLOCK storage
  sqlite.pragma('busy_timeout = 5000')
  sqlite.pragma('synchronous = NORMAL')
  sqlite.pragma('foreign_keys = ON')
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS user_dashboards (
      user_id TEXT NOT NULL, dashboard_id TEXT NOT NULL,
      layout_json TEXT NOT NULL, layout_version INTEGER NOT NULL DEFAULT 1,
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      PRIMARY KEY (user_id, dashboard_id));
    CREATE TABLE IF NOT EXISTS caldav_accounts (
      id TEXT PRIMARY KEY, user_id TEXT NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL,
      server_url TEXT NOT NULL, username TEXT NOT NULL, password_enc TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')));
    CREATE INDEX IF NOT EXISTS caldav_accounts_user_idx ON caldav_accounts(user_id);
    CREATE TABLE IF NOT EXISTS caldav_lists (
      id INTEGER PRIMARY KEY,
      account_id TEXT NOT NULL REFERENCES caldav_accounts(id) ON DELETE CASCADE,
      url TEXT NOT NULL, display_name TEXT, color TEXT,
      supports_vtodo INTEGER NOT NULL DEFAULT 1, enabled INTEGER NOT NULL DEFAULT 1,
      UNIQUE (account_id, url));
    CREATE TABLE IF NOT EXISTS _config_migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT (datetime('now')));
  `)
  console.log('sqlite config db ready at', path, '(journal_mode=' + sqlite.pragma('journal_mode', { simple: true }) + ')')
}

const bool = (v) => !!v && v !== 0 && v !== '0' && v !== 'f' && v !== 'false'

// ---- schema (postgres branch; sqlite already built above) ----
export async function initConfigSchema() {
  if (isSqlite) return
  await pool.query(`
    CREATE TABLE IF NOT EXISTS user_dashboards (
      user_id text NOT NULL, dashboard_id text NOT NULL,
      layout_json jsonb NOT NULL, layout_version integer NOT NULL DEFAULT 1,
      updated_at timestamptz NOT NULL DEFAULT now(),
      PRIMARY KEY (user_id, dashboard_id));
    CREATE TABLE IF NOT EXISTS caldav_accounts (
      id text PRIMARY KEY, user_id text NOT NULL, name text NOT NULL, type text NOT NULL,
      server_url text NOT NULL, username text NOT NULL, password_enc text NOT NULL,
      created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS caldav_lists (
      account_id text NOT NULL REFERENCES caldav_accounts(id) ON DELETE CASCADE,
      url text NOT NULL, display_name text, enabled boolean NOT NULL DEFAULT true,
      PRIMARY KEY (account_id, url));
    ALTER TABLE caldav_lists
      ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      ADD COLUMN IF NOT EXISTS color text,
      ADD COLUMN IF NOT EXISTS supports_vtodo boolean NOT NULL DEFAULT true;
    CREATE UNIQUE INDEX IF NOT EXISTS caldav_lists_id_uidx ON caldav_lists(id);
  `)
  console.log('postgres config schema ready')
}

// ============================================================
//  Dashboard layouts
// ============================================================
export async function getLayout(userId, dashboardId) {
  if (isSqlite) {
    const r = sqlite.prepare('SELECT layout_json, layout_version FROM user_dashboards WHERE user_id=? AND dashboard_id=?').get(userId, dashboardId)
    if (!r) return { layout: null }
    return { layout: JSON.parse(r.layout_json), version: r.layout_version }
  }
  const r = await pool.query('SELECT layout_json, layout_version FROM user_dashboards WHERE user_id=$1 AND dashboard_id=$2', [userId, dashboardId])
  if (!r.rows.length) return { layout: null }
  return { layout: r.rows[0].layout_json, version: r.rows[0].layout_version }
}

export async function saveLayout(userId, dashboardId, body) {
  const layout = body?.layout ?? body
  let version = Number(body?.layout?.version || body?.version || 1)
  if (!Number.isFinite(version)) version = 1
  version = Math.trunc(version)
  if (isSqlite) {
    sqlite.prepare(`INSERT INTO user_dashboards (user_id, dashboard_id, layout_json, layout_version, updated_at)
      VALUES (?,?,?,?,datetime('now'))
      ON CONFLICT(user_id, dashboard_id) DO UPDATE SET
        layout_json=excluded.layout_json, layout_version=excluded.layout_version, updated_at=datetime('now')`)
      .run(userId, dashboardId, JSON.stringify(layout), version)
    return
  }
  await pool.query(
    `INSERT INTO user_dashboards (user_id, dashboard_id, layout_json, layout_version, updated_at)
     VALUES ($1, $2, $3, $4, now())
     ON CONFLICT (user_id, dashboard_id)
     DO UPDATE SET layout_json = EXCLUDED.layout_json, layout_version = EXCLUDED.layout_version, updated_at = now()`,
    [userId, dashboardId, JSON.stringify(layout), version],
  )
}

// ============================================================
//  CalDAV accounts
// ============================================================
export async function listAccounts(userId) {
  if (isSqlite) return sqlite.prepare('SELECT * FROM caldav_accounts WHERE user_id=? ORDER BY created_at').all(userId)
  return (await pool.query('SELECT * FROM caldav_accounts WHERE user_id=$1 ORDER BY created_at', [userId])).rows
}

export async function getAccount(userId, id) {
  if (isSqlite) return sqlite.prepare('SELECT * FROM caldav_accounts WHERE id=? AND user_id=?').get(id, userId) || null
  return (await pool.query('SELECT * FROM caldav_accounts WHERE id=$1 AND user_id=$2', [id, userId])).rows[0] || null
}

export async function insertAccount(acc) {
  if (isSqlite) {
    sqlite.prepare('INSERT INTO caldav_accounts (id,user_id,name,type,server_url,username,password_enc) VALUES (?,?,?,?,?,?,?)')
      .run(acc.id, acc.user_id, acc.name, acc.type, acc.server_url, acc.username, acc.password_enc)
    return
  }
  await pool.query(
    'INSERT INTO caldav_accounts (id,user_id,name,type,server_url,username,password_enc) VALUES ($1,$2,$3,$4,$5,$6,$7)',
    [acc.id, acc.user_id, acc.name, acc.type, acc.server_url, acc.username, acc.password_enc],
  )
}

export async function deleteAccount(userId, id) {
  if (isSqlite) { sqlite.prepare('DELETE FROM caldav_accounts WHERE id=? AND user_id=?').run(id, userId); return }
  await pool.query('DELETE FROM caldav_accounts WHERE id=$1 AND user_id=$2', [id, userId])
}

export async function deleteAccountById(id) {
  if (isSqlite) { sqlite.prepare('DELETE FROM caldav_accounts WHERE id=?').run(id); return }
  await pool.query('DELETE FROM caldav_accounts WHERE id=$1', [id])
}

// Distinct users with at least one CalDAV account — the set the reminder poller sweeps.
export async function usersWithCaldav() {
  if (isSqlite) return sqlite.prepare('SELECT DISTINCT user_id FROM caldav_accounts').all().map((x) => x.user_id)
  return (await pool.query('SELECT DISTINCT user_id FROM caldav_accounts')).rows.map((x) => x.user_id)
}

// ============================================================
//  CalDAV lists
// ============================================================
export async function upsertList(accountId, { url, displayName, color, supportsVtodo }) {
  if (isSqlite) {
    sqlite.prepare(`INSERT INTO caldav_lists (account_id,url,display_name,color,supports_vtodo,enabled)
      VALUES (?,?,?,?,?,1)
      ON CONFLICT(account_id,url) DO UPDATE SET display_name=excluded.display_name, color=excluded.color, supports_vtodo=excluded.supports_vtodo`)
      .run(accountId, url, displayName, color, supportsVtodo ? 1 : 0)
    return
  }
  await pool.query(
    `INSERT INTO caldav_lists (account_id, url, display_name, color, supports_vtodo, enabled)
     VALUES ($1,$2,$3,$4,$5,true)
     ON CONFLICT (account_id, url) DO UPDATE SET display_name=EXCLUDED.display_name, color=EXCLUDED.color, supports_vtodo=EXCLUDED.supports_vtodo`,
    [accountId, url, displayName, color, supportsVtodo],
  )
}

export async function pruneLists(accountId, keepUrls) {
  if (!keepUrls || !keepUrls.length) return
  if (isSqlite) {
    sqlite.prepare(`DELETE FROM caldav_lists WHERE account_id=? AND url NOT IN (${keepUrls.map(() => '?').join(',')})`).run(accountId, ...keepUrls)
    return
  }
  await pool.query('DELETE FROM caldav_lists WHERE account_id=$1 AND url <> ALL($2::text[])', [accountId, keepUrls])
}

export async function listsForAccount(accountId) {
  if (isSqlite) {
    return sqlite.prepare('SELECT url, display_name, enabled FROM caldav_lists WHERE account_id=? ORDER BY display_name').all(accountId)
      .map((l) => ({ url: l.url, displayName: l.display_name, enabled: bool(l.enabled) }))
  }
  return (await pool.query('SELECT url, display_name, enabled FROM caldav_lists WHERE account_id=$1 ORDER BY display_name', [accountId])).rows
    .map((l) => ({ url: l.url, displayName: l.display_name, enabled: l.enabled }))
}

export async function enabledListsForAccount(accountId) {
  if (isSqlite) return sqlite.prepare('SELECT url, display_name FROM caldav_lists WHERE account_id=? AND enabled=1').all(accountId)
  return (await pool.query('SELECT url, display_name FROM caldav_lists WHERE account_id=$1 AND enabled=true', [accountId])).rows
}

export async function setListEnabled(accountId, url, enabled) {
  if (isSqlite) { sqlite.prepare('UPDATE caldav_lists SET enabled=? WHERE account_id=? AND url=?').run(enabled ? 1 : 0, accountId, url); return }
  await pool.query('UPDATE caldav_lists SET enabled=$1 WHERE account_id=$2 AND url=$3', [enabled, accountId, url])
}

// Lists with their stable integer id (= project_id) AND their account creds, so
// the task store can fan out reads/writes without a second query per list.
export async function listsWithId(userId) {
  if (isSqlite) {
    return sqlite.prepare(
      `SELECT l.id, l.url, l.display_name, l.color, l.supports_vtodo, l.enabled,
              a.id AS account_id, a.type AS account_type, a.server_url AS account_server_url,
              a.username AS account_username, a.password_enc AS account_password_enc
       FROM caldav_lists l JOIN caldav_accounts a ON a.id = l.account_id
       WHERE a.user_id = ? ORDER BY l.id`).all(userId)
      .map((r) => ({ ...r, supports_vtodo: bool(r.supports_vtodo), enabled: bool(r.enabled) }))
  }
  return (await pool.query(
    `SELECT l.id, l.url, l.display_name, l.color, l.supports_vtodo, l.enabled,
            a.id AS account_id, a.type AS account_type, a.server_url AS account_server_url,
            a.username AS account_username, a.password_enc AS account_password_enc
     FROM caldav_lists l JOIN caldav_accounts a ON a.id = l.account_id
     WHERE a.user_id = $1 ORDER BY l.id`, [userId])).rows
}

// Resolve a list id to { list, account } (ownership-checked) for CRUD.
export async function getListById(userId, listId) {
  const map = (x) => ({
    list: { id: x.list_id, url: x.list_url, displayName: x.display_name, color: x.color, supportsVtodo: bool(x.supports_vtodo), enabled: bool(x.enabled) },
    account: { id: x.account_id, user_id: x.user_id, name: x.name, type: x.type, server_url: x.server_url, username: x.username, password_enc: x.password_enc },
  })
  if (isSqlite) {
    const x = sqlite.prepare(
      `SELECT l.id AS list_id, l.url AS list_url, l.display_name, l.color, l.supports_vtodo, l.enabled,
              a.id AS account_id, a.user_id, a.name, a.type, a.server_url, a.username, a.password_enc
       FROM caldav_lists l JOIN caldav_accounts a ON a.id = l.account_id
       WHERE l.id = ? AND a.user_id = ?`).get(listId, userId)
    return x ? map(x) : null
  }
  const r = await pool.query(
    `SELECT l.id AS list_id, l.url AS list_url, l.display_name, l.color, l.supports_vtodo, l.enabled,
            a.id AS account_id, a.user_id, a.name, a.type, a.server_url, a.username, a.password_enc
     FROM caldav_lists l JOIN caldav_accounts a ON a.id = l.account_id
     WHERE l.id = $1 AND a.user_id = $2`, [listId, userId])
  return r.rows.length ? map(r.rows[0]) : null
}

// ============================================================
//  Sessions
// ============================================================
export function createSessionStore() {
  if (isSqlite) {
    const SqliteStore = sqliteStoreFactory(session)
    return new SqliteStore({ client: sqlite, expired: { clear: true, intervalMs: 15 * 60 * 1000 } })
  }
  const PgStore = connectPgSimple(session)
  return new PgStore({ pool, createTableIfMissing: true })
}

// ============================================================
//  One-time config migration: Postgres -> SQLite (removed in P6)
// ============================================================
// On the first boot with CONFIG_STORE=sqlite, copy the small config tables over
// from Postgres so the user keeps their linked CalDAV account + dashboard layout
// across the cutover. Idempotent: only runs when the SQLite config is empty.
export async function migrateConfigFromPostgres() {
  if (!isSqlite || !sqlite) return
  const have = sqlite.prepare('SELECT (SELECT COUNT(*) FROM caldav_accounts)+(SELECT COUNT(*) FROM user_dashboards) AS n').get().n
  if (have > 0) return
  try {
    const accts = (await pool.query('SELECT * FROM caldav_accounts')).rows
    const lists = (await pool.query('SELECT * FROM caldav_lists')).rows
    const dash = (await pool.query('SELECT * FROM user_dashboards')).rows
    if (!accts.length && !dash.length) return
    const insAcc = sqlite.prepare('INSERT OR IGNORE INTO caldav_accounts (id,user_id,name,type,server_url,username,password_enc) VALUES (?,?,?,?,?,?,?)')
    const insList = sqlite.prepare('INSERT OR IGNORE INTO caldav_lists (id,account_id,url,display_name,color,supports_vtodo,enabled) VALUES (?,?,?,?,?,?,?)')
    const insDash = sqlite.prepare('INSERT OR IGNORE INTO user_dashboards (user_id,dashboard_id,layout_json,layout_version) VALUES (?,?,?,?)')
    sqlite.transaction(() => {
      for (const a of accts) insAcc.run(a.id, a.user_id, a.name, a.type, a.server_url, a.username, a.password_enc)
      for (const l of lists) insList.run(l.id, l.account_id, l.url, l.display_name, l.color, l.supports_vtodo ? 1 : 0, l.enabled ? 1 : 0)
      for (const d of dash) insDash.run(d.user_id, d.dashboard_id, JSON.stringify(d.layout_json), d.layout_version)
    })()
    console.log(`config migrated from postgres: ${accts.length} accounts, ${lists.length} lists, ${dash.length} layouts`)
  } catch (e) {
    console.error('config migration from postgres skipped (non-fatal):', e?.message || e)
  }
}
